version: '3.1'
services:
  wordpress:
    image: wordpress:5.8.2-php8.0-apache
    restart: 'no'
    ports:
      - '${WP_PORT:-8000}:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: '${DB_USER}'
      WORDPRESS_DB_PASSWORD: '${DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${DB_NAME}'
      WORDPRESS_DEBUG: '${WORDPRESS_DEBUG:-0}'
      WORDPRESS_TABLE_PREFIX: '${DB_PREFIX:-wp_}'
      WORDPRESS_CONFIG_EXTRA: |
        require __DIR__.'/vendor/autoload.php';
        define('WP_DEBUG_DISPLAY', false);
        define('MONOLOG_LOG_NAME', getenv_docker('MONOLOG_LOG_NAME', 'wordpress.log'));
        define('MONOLOG_LOG_DAYS', getenv_docker('MONOLOG_LOG_DAYS', 30));
        define('MONOLOG_LOG_LEVEL', getenv_docker('MONOLOG_LOG_LEVEL', \Monolog\Logger::WARNING));
        require __DIR__.'/monolog.php';
    volumes:
      - ./wordpress:/var/www/html
      - ./src/plugins:/var/www/html/wp-content/plugins
      - ./src/mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./src/themes:/var/www/html/wp-content/themes
      - ./src/monolog.php:/var/www/html/monolog.php
    depends_on:
      - db
    networks:
      - wordpress
  cli:
    image: wordpress:cli-php8.0
    entrypoint: [ 'php', '-d', 'memory_limit=-1', '/usr/local/bin/wp' ]
    restart: 'no'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: '${DB_USER}'
      WORDPRESS_DB_PASSWORD: '${DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${DB_NAME}'
      WORDPRESS_DEBUG: '${WORDPRESS_DEBUG:-0}'
      WORDPRESS_TABLE_PREFIX: '${DB_PREFIX:-wp_}'
      WORDPRESS_CONFIG_EXTRA: |
        require '/var/www/html/vendor/autoload.php';
        define('WP_DEBUG_DISPLAY', false);
        define('MONOLOG_LOG_NAME', getenv_docker('MONOLOG_LOG_NAME', 'wordpress.log'));
        define('MONOLOG_LOG_DAYS', getenv_docker('MONOLOG_LOG_DAYS', 30));
        define('MONOLOG_LOG_LEVEL', getenv_docker('MONOLOG_LOG_LEVEL', \Monolog\Logger::EMERGENCY));
        require '/var/www/html/monolog.php';
    volumes:
      - ./wordpress:/var/www/html
      - ~/.wp-cli:/home/www-data/.wp-cli/
      - ./src/plugins:/var/www/html/wp-content/plugins
      - ./src/mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./src/themes:/var/www/html/wp-content/themes
      - ./src/monolog.php:/var/www/html/monolog.php
    depends_on:
      - db
    networks:
      - wordpress
  db:
    image: mysql:8.0
    restart: 'no'
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - '${DB_PUBLISH_PORT:-3306}:3306'
    volumes:
      - database:/var/lib/mysql
    networks:
      - wordpress
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - wordpress
  npm:
    image: node:14.17
    working_dir: /app
    entrypoint: npm
    command: run watch
    ports:
      - 8080:8080
    restart: 'no'
    volumes:
      - .:/app
    networks:
      - wordpress
  composer:
    image: composer/composer
    restart: 'no'
    command: install
    volumes:
      - ./:/app
    networks:
      - wordpress

networks:
  wordpress:
    driver: bridge

volumes:
  database:
#  custom.ini:$PHP_INI_DIR/conf.d/
#  /usr/local/etc/php/php.ini
